shallow_clone: true

# version format
version: 2.0.{build}

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# Do not build on tags (GitHub only)
skip_tags: true

configuration: Release

# Assembly Info
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"


environment:
  sign_tool: 'C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin\signtool.exe'
  timestamp_url: http://timestamp.verisign.com/scripts/timstamp.dll
  pfx_file: 'C:\projects\Network-AutoSwitch\Tulpep.pfx'
  pfx_password:
    secure: LdcyoQhXm2P2QuFz/ogRYpACnJeZDyka/QBzMKJkKKE=


before_build:
  - nuget restore


after_build:
  - cmd: '"%sign_tool%" sign /f "%pfx_file%" /p %pfx_password% /t %timestamp_url% "C:\projects\network-autoswitch\Tulpep.NetworkAutoSwitch.NetworkService\bin\Release\NetworkAutoSwitch.exe"'
  - cmd: '"%sign_tool%" sign /f "%pfx_file%" /p %pfx_password% /t %timestamp_url% "C:\projects\network-autoswitch\Tulpep.NetworkAutoSwitch.ProxyService\bin\Release\ProxyAutoSwitch.exe"'

artifacts:
  - path: '**\bin\Release\NetworkAutoSwitch.exe'
    name: NetworkAutoSwitch.exe

  - path: '**\bin\Release\ProxyAutoSwitch.exe'
    name: ProxyAutoSwitch.exe

deploy:
  release: Network-AutoSwitch $(appveyor_build_version)
  provider: GitHub
  description: ''
  auth_token:
    secure: Q+20Xaui8ng5gVvoMIkb0g4F0oqMZFVOJo4SNRc+KVN91WkjLe5gTMkifCyDZTlE
  artifact: /.*\.exe/
  draft: false
  prerelease: false
  on:
    branch: master
